package com.tiantianmeitu.background.mapper;

import com.tiantianmeitu.background.bean.Keyword;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface KeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer keywordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbggenerated
     */
    int insert(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbggenerated
     */
    Keyword selectByPrimaryKey(Integer keywordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbggenerated
     */
    List<Keyword> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Keyword record);
}