package com.tiantianmeitu.background.mapper;

import com.tiantianmeitu.background.bean.PostKeywordRel;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PostKeywordRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_keyword_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer postKeywordRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_keyword_rel
     *
     * @mbggenerated
     */
    int insert(PostKeywordRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_keyword_rel
     *
     * @mbggenerated
     */
    PostKeywordRel selectByPrimaryKey(Integer postKeywordRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_keyword_rel
     *
     * @mbggenerated
     */
    List<PostKeywordRel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_keyword_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PostKeywordRel record);
}