package com.tiantianmeitu.background.bean;

import java.io.Serializable;
import java.util.Date;

public class Keyword implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.keyword_id
     *
     * @mbggenerated
     */
    private Integer keywordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.order_no
     *
     * @mbggenerated
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.operate_type
     *
     * @mbggenerated
     */
    private String operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.operate_time
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table keyword
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.keyword_id
     *
     * @return the value of keyword.keyword_id
     *
     * @mbggenerated
     */
    public Integer getKeywordId() {
        return keywordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.keyword_id
     *
     * @param keywordId the value for keyword.keyword_id
     *
     * @mbggenerated
     */
    public void setKeywordId(Integer keywordId) {
        this.keywordId = keywordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.name
     *
     * @return the value of keyword.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.name
     *
     * @param name the value for keyword.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.order_no
     *
     * @return the value of keyword.order_no
     *
     * @mbggenerated
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.order_no
     *
     * @param orderNo the value for keyword.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.operate_type
     *
     * @return the value of keyword.operate_type
     *
     * @mbggenerated
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.operate_type
     *
     * @param operateType the value for keyword.operate_type
     *
     * @mbggenerated
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.operate_time
     *
     * @return the value of keyword.operate_time
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.operate_time
     *
     * @param operateTime the value for keyword.operate_time
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", keywordId=").append(keywordId);
        sb.append(", name=").append(name);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", operateType=").append(operateType);
        sb.append(", operateTime=").append(operateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}