package com.tiantianmeitu.background.bean;

import java.io.Serializable;

public class PostKeywordRel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_keyword_rel.post_keyword_rel_id
     *
     * @mbggenerated
     */
    private Integer postKeywordRelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_keyword_rel.post_id
     *
     * @mbggenerated
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_keyword_rel.keyword_id
     *
     * @mbggenerated
     */
    private Integer keywordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post_keyword_rel
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_keyword_rel.post_keyword_rel_id
     *
     * @return the value of post_keyword_rel.post_keyword_rel_id
     *
     * @mbggenerated
     */
    public Integer getPostKeywordRelId() {
        return postKeywordRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_keyword_rel.post_keyword_rel_id
     *
     * @param postKeywordRelId the value for post_keyword_rel.post_keyword_rel_id
     *
     * @mbggenerated
     */
    public void setPostKeywordRelId(Integer postKeywordRelId) {
        this.postKeywordRelId = postKeywordRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_keyword_rel.post_id
     *
     * @return the value of post_keyword_rel.post_id
     *
     * @mbggenerated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_keyword_rel.post_id
     *
     * @param postId the value for post_keyword_rel.post_id
     *
     * @mbggenerated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_keyword_rel.keyword_id
     *
     * @return the value of post_keyword_rel.keyword_id
     *
     * @mbggenerated
     */
    public Integer getKeywordId() {
        return keywordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_keyword_rel.keyword_id
     *
     * @param keywordId the value for post_keyword_rel.keyword_id
     *
     * @mbggenerated
     */
    public void setKeywordId(Integer keywordId) {
        this.keywordId = keywordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_keyword_rel
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", postKeywordRelId=").append(postKeywordRelId);
        sb.append(", postId=").append(postId);
        sb.append(", keywordId=").append(keywordId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}